# (Add, Key, Value), (Delete, Key), (Search, Key)
OPERATIONS = [
    ("Add", "Hello", 50),
    ("Add", "Goodbye", 20),
    ("Add", "Data", 40),
    ("Add", "Algorithm", 60),
    ("Add", "Visual", 50),
    ("Delete", "Goodbye"),
    ("Delete", "Data"),
    ("Add", "Collision", 20),
    ("Add", "Python", 40),
    ("Add", "Liam", 60),
    ("Delete", "Visual"),
    ("Add", "Pygame", 50),
    ("Add", "Graphs", 20),
    ("Delete", "Hello"),
    ("Delete", "Algorithm"),
    ("Add", "Sorted", 40),
    ("Add", "Operation", 60),
    ("Search", "Liam"),
    ("Delete", "Pygame"),
    ("Search", "Pygame"),
]